### ISSUE TITLE
null is not an object(evaluating"ThreadManager StartThread")

### ISSUE THREAD

**Issue by Libra11** [joltup/react-native-threads#88] opened 2019-11-01 08:25 UTC
I got this error in RN 0.61.3  
IOS system
![image](https://libra321.oss-cn-huhehaote.aliyuncs.com/1C6A102F-931F-408F-9406-06DD6BC1CC57.png)

**Comment by Genhain** [comment] 2019-11-04 07:36
Also experiencing this issue on the simulator

**Comment by dorthwein** [comment] 2019-11-14 17:45
Sames

**Comment by ihavenoface5** [comment] 2019-11-14 17:53
You will need manually link the library. See 
Duplicate of #86 #39 #79

**Closed** 2019-11-28 03:45 UTC
